name: full_stack_project_oc
services:
  db:
    container_name: full_stack_app_db
    image: mysql:8.4.3
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: network
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    env_file:
      - path: .env
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge
