name: full_stack_project_oc
services:
  db:
    container_name: full_stack_app_db
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: network
    restart: unless-stopped
    env_file:
      - path: .env
